# Generated by Django 3.2.18 on 2023-06-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_no', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=500)),
                ('notice_content', models.TextField(blank=True, null=True)),
                ('context_img', models.ImageField(upload_to='')),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항 관리',
            },
        ),
    ]
